config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :microposts do
    resources :comments
    member do
      patch :publish
    end
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :micropost
    belongs_to :user
    validates :user_id, presence: true
    validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


    def create
        @micropost = Micropost.find(params[:micropost_id])
        @comment = @micropost.comments.new(comment_params)
        @comment.user = current_user   
        if @comment.save
            flash[:success] = "berhasil"
        else
            flash[:notice] = "ada error"
        end
        redirect_to micropost_comments_path(@micropost)
    end

    def destroy
        @micropost = Micropost.find(params[:micropost_id])
        @micropost.comments.find(params[:id]).destroy
        flash[:success] = "deleted successfully!"
        redirect_to micropost_comments_path(@micropost)
    end

    def index
        @micropost = Micropost.find(params[:micropost_id])
        @comment = Comment.all
    end

    def new
        @comment = Comment.new
    end

    def edit
        @micropost = Micropost.find(params[:micropost_id])
        @comment = @micropost.comments.find(params[:id])
    end

    def show
    end

    def update
        @micropost = Micropost.find(params[:micropost_id])
        @comment = Comment.find(params[:id])
        if @comment.update(comment_params)
            flash[:success] = "Updated Successfully!"
            redirect_to micropost_comments_path(@micropost)
        else
            render 'edit'
        end

    end

    private
    
        def comment_params 
            params
            .require(:comment)
            .permit(:content)
        end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= user.name %>
<%= comment.body %>
Sent <%= time_ago_in_words(comment.created_at) %> ago.

app/views/comments/_form.html.erb
<%= form_for([@micropost, @micropost.comments.build]) do |f| %>
    <p>
        <%= f.label "Post comment" %> <br />
        <%= f.text_area :content %>
    </p>
    <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3><br /><br />

<%= form_with(model: [@micropost, @comment], local: true) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            
            <%= f.label :content %>
            <%= f.text_field :content, class: 'form-control' %>
            
            <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/comments/index.html.erb
<h3>Micropost Details</h3><br />
<div>
    <strong>Post Content:</strong>
    <%= @micropost.content %>
</div>
<br /><br />
<strong><%= @micropost.comments.count %> Comments</strong>
<br />
<% @micropost.comments.each do |comment| %>
    <%= comment.content %>
    <%= link_to "Edit", edit_micropost_comment_path(@micropost, comment) %>

    <%= link_to "Delete", micropost_comment_path(@micropost, comment), 
    method: :delete, data: { confirm: "Are you sure?" } %>
    <br />
<% end %>
<br/><br /><br />
<%= render 'comments/form' %>
<br/>