config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :microposts do
    resources :comments
    member do
      patch :publish
    end
  end
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord

  enum status: { draft: "draft", published: "published" }

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: "must be a valid image format" }, 
  size: { less_than: 5.megabytes, message: "should be less than 5MB" }

  # Returns a resized image for display.
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

    def create
        @micropost = current_user.microposts.build(micropost_params)
        @micropost.image.attach(params[:micropost][:image])
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            render 'static_pages/home'
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end

    def publish
        @micropost = Micropost.find(params[:id])
        @micropost.update(status: "published")
        flash[:success] = "Post published!"
        redirect_to root_url
    end

    private

    def micropost_params
        params.require(:micropost).permit(:content, :image)
    end

    def correct_user
        @micropost = current_user.microposts.find_by(id: params[:id])
        redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<% if current_user?(micropost.user) || micropost.status == 'published' %>

    <li id="micropost-<%= micropost.id %>">
        <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
        <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
        <span class="content">
            <%= micropost.content %>
            <%= image_tag micropost.display_image if micropost.image.attached? %>
        </span>
        <span class="timestamp">
            Posted <%= time_ago_in_words(micropost.created_at) %> ago.
            <% if current_user?(micropost.user) %>
                <%= link_to "delete", micropost, method: :delete,
                data: { confirm: "You sure?" } %>
            <% end %>
        </span>
    </li>
    Status: <%= micropost.status %><br />
    <%= link_to "Show", micropost_comments_path(micropost) %>
    <% if current_user?(micropost.user) %>
        <% if micropost.status == 'draft' %>
            <%= link_to "Publish", publish_micropost_path(micropost), method: :patch, data: { confirm: "Are you sure?" } %>
        <% end %>
    <% end %>
    
<% end %>